"""empty message

Revision ID: 8491f9398ba1
Revises: 
Create Date: 2025-04-19 02:38:31.245334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8491f9398ba1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.alter_column('tipo_veiculo',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('CARRO', 'MOTO', 'CAMINHONETE', 'VAN', 'OUTRO', name='tipoveiculo'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.alter_column('tipo_veiculo',
               existing_type=sa.Enum('CARRO', 'MOTO', 'CAMINHONETE', 'VAN', 'OUTRO', name='tipoveiculo'),
               type_=sa.VARCHAR(length=5),
               nullable=True)

    # ### end Alembic commands ###
