"""Adicionei coluna nova

Revision ID: 96403d7f38e3
Revises: 
Create Date: 2025-04-15 01:00:26.630900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96403d7f38e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitante')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitante',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('casa_destino', sa.VARCHAR(length=20), nullable=False),
    sa.Column('hora_entrada', sa.DATETIME(), nullable=True),
    sa.Column('hora_limite', sa.DATETIME(), nullable=False),
    sa.Column('placa', sa.VARCHAR(length=20), nullable=True),
    sa.Column('foto_visitante', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
