"""Corrige painel porteiro

Revision ID: b536904b86ad
Revises: 8491f9398ba1
Create Date: 2025-04-19 03:29:35.496874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b536904b86ad'
down_revision = '8491f9398ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.alter_column('tipo_veiculo',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.alter_column('tipo_veiculo',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)

    # ### end Alembic commands ###
