"""empty message

Revision ID: c7735ed78694
Revises: b536904b86ad
Create Date: 2025-04-20 19:14:36.119691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7735ed78694'
down_revision = 'b536904b86ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.create_index('idx_movimentacao_entrada', ['entrada'], unique=False)
        batch_op.create_index('idx_movimentacao_saida', ['saida'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.drop_index('idx_movimentacao_saida')
        batch_op.drop_index('idx_movimentacao_entrada')

    # ### end Alembic commands ###
